export type PoliticalLean =
  | "Right"
  | "Right-center"
  | "Center"
  | "Left-center"
  | "Left";
export type BiasIntensity = "Highly Biased" | "Slightly Biased" | "Neutral";
export type Domain = "headline" | "article";

export interface Prediction {
  id: number;
  text: string;
  source: string;
  domain: Domain;
  lean: PoliticalLean;
  intensity: BiasIntensity;
  leanConfidence: number;
  intensityConfidence: number;
  confidence: number;
  chunkAttention: number[];
}

export const LEAN_LABELS: PoliticalLean[] = [
  "Left",
  "Left-center",
  "Center",
  "Right-center",
  "Right",
];

export const INTENSITY_LABELS: BiasIntensity[] = [
  "Neutral",
  "Slightly Biased",
  "Highly Biased",
];

export const LEAN_COLORS: Record<PoliticalLean, string> = {
  Left: "oklch(0.55 0.15 240)",
  "Left-center": "oklch(0.6 0.12 210)",
  Center: "oklch(0.7 0.15 160)",
  "Right-center": "oklch(0.65 0.15 50)",
  Right: "oklch(0.6 0.2 30)",
};

export const INTENSITY_COLORS: Record<BiasIntensity, string> = {
  Neutral: "oklch(0.7 0.15 160)",
  "Slightly Biased": "oklch(0.75 0.1 80)",
  "Highly Biased": "oklch(0.6 0.2 30)",
};

export const predictions: Prediction[] = [
  {
    id: 1,
    text: "Government announces sweeping new tax reforms targeting wealthy",
    source: "CNN",
    domain: "headline",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.82,
    intensityConfidence: 0.74,
    confidence: 0.82,
    chunkAttention: [0.85],
  },
  {
    id: 2,
    text: "Democrats push radical spending bill despite economic warnings from experts",
    source: "Fox News",
    domain: "headline",
    lean: "Right",
    intensity: "Highly Biased",
    leanConfidence: 0.91,
    intensityConfidence: 0.88,
    confidence: 0.91,
    chunkAttention: [0.92],
  },
  {
    id: 3,
    text: "Senate passes bipartisan infrastructure deal with broad support from both parties",
    source: "Reuters",
    domain: "headline",
    lean: "Center",
    intensity: "Neutral",
    leanConfidence: 0.87,
    intensityConfidence: 0.91,
    confidence: 0.91,
    chunkAttention: [0.55],
  },
  {
    id: 4,
    text: "The recent climate legislation represents a significant step forward in addressing environmental concerns, though critics argue the measures don't go far enough to meet international targets.",
    source: "The Guardian",
    domain: "article",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.76,
    intensityConfidence: 0.69,
    confidence: 0.76,
    chunkAttention: [0.72, 0.45, 0.61],
  },
  {
    id: 5,
    text: "Republican leaders expose wasteful government spending in shocking report",
    source: "Breitbart",
    domain: "headline",
    lean: "Right",
    intensity: "Highly Biased",
    leanConfidence: 0.94,
    intensityConfidence: 0.85,
    confidence: 0.94,
    chunkAttention: [0.88],
  },
  {
    id: 6,
    text: "Healthcare reform proposals aim to extend coverage to uninsured Americans. Supporters point to potential long-term savings while opponents cite concerns about government overreach.",
    source: "AP News",
    domain: "article",
    lean: "Center",
    intensity: "Neutral",
    leanConfidence: 0.83,
    intensityConfidence: 0.86,
    confidence: 0.86,
    chunkAttention: [0.51, 0.48, 0.52],
  },
  {
    id: 7,
    text: "Progressive activists demand immediate action on student debt crisis",
    source: "MSNBC",
    domain: "headline",
    lean: "Left",
    intensity: "Highly Biased",
    leanConfidence: 0.89,
    intensityConfidence: 0.82,
    confidence: 0.89,
    chunkAttention: [0.9],
  },
  {
    id: 8,
    text: "Immigration policy changes spark debate. Advocacy groups argue the changes disproportionately impact families, while security officials defend the measures as necessary.",
    source: "BBC",
    domain: "article",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.71,
    intensityConfidence: 0.65,
    confidence: 0.71,
    chunkAttention: [0.65, 0.55, 0.7],
  },
  {
    id: 9,
    text: "Economy adds 250,000 jobs in strong monthly report beating expectations",
    source: "Bloomberg",
    domain: "headline",
    lean: "Center",
    intensity: "Neutral",
    leanConfidence: 0.85,
    intensityConfidence: 0.89,
    confidence: 0.89,
    chunkAttention: [0.48],
  },
  {
    id: 10,
    text: "Conservative commentators rally against so-called woke corporate policies destroying American values",
    source: "Daily Wire",
    domain: "headline",
    lean: "Right",
    intensity: "Highly Biased",
    leanConfidence: 0.93,
    intensityConfidence: 0.91,
    confidence: 0.93,
    chunkAttention: [0.95],
  },
  {
    id: 11,
    text: "Trade negotiations continue between major powers. Diplomats from both sides have expressed cautious optimism about reaching a deal before year-end.",
    source: "Financial Times",
    domain: "article",
    lean: "Center",
    intensity: "Neutral",
    leanConfidence: 0.88,
    intensityConfidence: 0.92,
    confidence: 0.92,
    chunkAttention: [0.5, 0.47, 0.53],
  },
  {
    id: 12,
    text: "Workers demand living wage as corporate profits soar to record heights",
    source: "HuffPost",
    domain: "headline",
    lean: "Left",
    intensity: "Highly Biased",
    leanConfidence: 0.86,
    intensityConfidence: 0.79,
    confidence: 0.86,
    chunkAttention: [0.87],
  },
  {
    id: 13,
    text: "Supreme Court ruling may reshape voting rights landscape",
    source: "NPR",
    domain: "headline",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.73,
    intensityConfidence: 0.68,
    confidence: 0.73,
    chunkAttention: [0.71],
  },
  {
    id: 14,
    text: "Defense spending bill clears committee amid fierce partisan disagreement. Opposition members criticized the lack of funding for domestic programs.",
    source: "Washington Post",
    domain: "article",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.74,
    intensityConfidence: 0.71,
    confidence: 0.74,
    chunkAttention: [0.68, 0.52, 0.64],
  },
  {
    id: 15,
    text: "Tech companies resist government overreach in new data privacy regulation",
    source: "Wall Street Journal",
    domain: "headline",
    lean: "Right-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.78,
    intensityConfidence: 0.72,
    confidence: 0.78,
    chunkAttention: [0.74],
  },
  {
    id: 16,
    text: "Gun control advocates may be overreacting to recent policy changes according to analysts",
    source: "The Hill",
    domain: "headline",
    lean: "Right-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.75,
    intensityConfidence: 0.66,
    confidence: 0.75,
    chunkAttention: [0.69],
  },
  {
    id: 17,
    text: "Education reform gains momentum as states adopt new standards. Teachers unions have raised concerns about implementation timelines and adequate training resources.",
    source: "The Atlantic",
    domain: "article",
    lean: "Left-center",
    intensity: "Slightly Biased",
    leanConfidence: 0.7,
    intensityConfidence: 0.63,
    confidence: 0.7,
    chunkAttention: [0.6, 0.48, 0.57],
  },
  {
    id: 18,
    text: "Patriotic Americans push back against attempts to rewrite national history in schools",
    source: "New York Post",
    domain: "headline",
    lean: "Right",
    intensity: "Highly Biased",
    leanConfidence: 0.9,
    intensityConfidence: 0.84,
    confidence: 0.9,
    chunkAttention: [0.91],
  },
  {
    id: 19,
    text: "Federal Reserve signals potential rate changes. Bond yields shifted modestly while equity markets remained relatively stable.",
    source: "CNBC",
    domain: "article",
    lean: "Center",
    intensity: "Neutral",
    leanConfidence: 0.9,
    intensityConfidence: 0.93,
    confidence: 0.93,
    chunkAttention: [0.52, 0.49, 0.5],
  },
  {
    id: 20,
    text: "Community organizers fight for environmental justice in underserved neighborhoods left behind by policymakers",
    source: "The Nation",
    domain: "headline",
    lean: "Left",
    intensity: "Highly Biased",
    leanConfidence: 0.88,
    intensityConfidence: 0.81,
    confidence: 0.88,
    chunkAttention: [0.86],
  },
];